FORMAT: 1A
HOST: http://apistaging.yoolk.com

# Yoolk REST API CHANGE
An API for Yoolk

# Group Notes
Notes related resources of the **Notes API**

## Notes Collection [/notes]
### List all Notes [GET]
+ Response 200 (application/json)

        [
          {
            "id": 1, "title": "Jogging in park", text: "Just awesome", score: 1
          },
          {
            "id": 2, "title": "Pick-up posters from post-office", title: "Never been good", score: 2
          }
        ]

### Create a Note [POST]
+ Request (application/json)

        {
          "note": {
            "title": "Look this way",
            "text": "I think it's good",
            score: 6
          }
        }

+ Response 201 (application/json)

        {
          "id": 3,
          "title": "Look this way",
          "text": "I think it's good",
          score: 6
        }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            {
              "id": 3,
              "title": "Look this way",
              "text": "I think it's good",
              score: 6
            }

### Remove a Note [DELETE]
+ Response 204
